using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Astrologia
{
    public partial class frmAstrolojiNedir : Form
    {
        public frmAstrolojiNedir()
        {
            InitializeComponent();
        }

        private void frmAstrolojiNedir_Load(object sender, EventArgs e)
        {
            lblAstrolojiNedir.Text = "Astroloji, göksel cisimlerin ve astronomik fenomenlerin, insan karakteri ve kaderi üzerine etkilerinin olduğu önermesini konu alan, bilimsel gerçekliğe sahip olmayan sözde bilimdir. Yunanca yıldız anlamına gelen 'astro' ve bilgi anlamına gelen 'logos' kelimelerinden türemiştir. Astroloji insanlara gelecekte yaşanacak olaylardan haberdar edebileceğini iddia eder fakat bu iddialar bilim camiasında kesin olarak yalanlanmıştır ve bu sebepten ötürü Astroloji bir Sözde bilim'dir. Eskiden astrologlar gök günlüğü adı verilen ve gökyüzü konumunun gün, ay ve yıl olarak gösteren bir kitap ve ev tabloları kullanarak Yıldız Haritası grafiğini çıkartırlardı. Bunların doğruluğu tıpkı Astrolojinin diğer iddiaları ile birlikte bilimsel literatürde geçerli değildir. Tüm bu yalanlamalara rağmen, astroloji halâ popülerliğini sürdürmektedir. Hiçbir bilimsel kanıta dayanmamaktadır.\n" +
                "\nTarihçe\n" +
                "\nGök olaylarına bakarak kehanetlerde bulunmak, özellikle de felaketleri kestirmek, tarihte pek çok toplumda gözlenmiştir.Bunun ilk yazılı örneği Mezopotamya'daki Asur ve Babil uygarlıklarındadır. Tarihinin çoğu boyunca astroloji, bilimsel bir gelenek olarak siyasi ve akademik bağlamlarda kabul edildi ve astronomi, simya, meteoroloji ve tıp gibi diğer çalışmalarla bağdaştırıldı. 17.yüzyılın sonunda, astronomi ve fizikteki(gün merkezlilik ve Newton mekaniği gibi) yeni bilimsel kavramlar astrolojiyi sorguladı.Astroloji böylece akademik ve teorik duruşunu kaybetti ve astrolojiye olan yaygın inanç büyük ölçüde azaldı.Günümüzde Astrolojinin bilimsel bir geçerliliği yoktur. Günümüzde Batı'da var olan astroloji sisteminin kökeni Eski Yunan'dan gelmektedir. Büyük İskender dönemine kadar, Eski Yunan'daki gökyüzü incelemeleri yeryüzünde olan olayların açıklamasını ve kehanetleri içermezdi. Gelecekle ilgili tahminler, gökyüzü cisimlerinin hava durumunu etkiliyor olduğu görüşünden ibaretti. Bu dönemden sonra Mezopotamya uygarlıklarının etkisi ile Eski Yunan'da astronominin yanı sıra astroloji de boy göstermeye başlamıştır. Bundan çok uzun zaman önce, insanlar geceleyin yıldızlı gökyüzüne bakmış ve bu yıldızların ne olduğunu, yaşamları üstünde ne etkiler yaptığını merak etmişlerdir. Başlangıçtaki bu sorulardan astroloji doğdu.Hiç kimse, astrolojinin yazı öncesi geleneğinin ne kadar eski olduğunu tam olarak bilmemektedir. Astrolojinin yazılı tarihte ilk ortaya çıkışı ise MÖ 2500 yılında, gezegenlerin insanın kaderini etkileyen güçlü tanrılar olduğuna inanılan Mezopotamya'da olmuştur. Bu astrologlar gökyüzünü dikkatle izlemeye ve onun geceleri parıltılı, muhteşem sessizliğinde gördüklerinde düzenli kayıtlarını tutmaya başlamışlardır. Astroloji danışmanları Kraliyet ailesine devlet yönetimi konusunda akıl verirlerdi ve Mezopotamya tarihinin erken dönemlerinde astroloji 'kraliyet sanatı' olarak düşünülmüştür. Mezopotamya gökbilimcileri göklerin işleyişini açıklamak için yeni geometri bilimini kullanmaya başladıkları sıralarda, eski Yunanlar, zaten tanrılarının geniş panteonuyla övünmekteydiler.Yunanlar, Mezopotamya'nın astrolojik kehanet biçimini kendi mitolojileri ve yeni geometri bilimiyle birleştirip zodyak dayanan kişisel bir astroloji geliştirdiler. Yunanca 'zodiakos kyklos' ya da 'hayvanlar dairesi' anlamına gelen bu kuşak, Güneş'in bir yıl boyunca gökyüzünde izlediği eliptik yörüngesinin her iki yanında dokuz derece uzanır.Zodyak Koç, Boğa, Yengeç gibi her biri bir hayvan tarafından simgelenen ve yılın belirleyen on iki parçaya bölünmüştür. Böylece Yunanlar astrolojiyi göklerinin yaşamlarındaki etkilerini merak eden bireylere danışmanlıkta kullanarak yıldız falını ortaya çıkarmışlardır.Ancak, astroloji Hristiyan öğretisinin içine sızdı ve gelişmeye devam etti.\n" +
                "\nBatı Astrolojisi\n" +
                "\nYıldız Haritası\n" +
                "\nYıldız Haritası günümüzde yaygın olarak kabul edilen Batı astrolojisinde İlkbahar Ekinoksu(Nevruz) esas alınarak çıkartılmıştır.Çıkartılan bu haritanın takımyıldızlarıyla bir alakası bulunmamaktadır. 0 Derece Koç burcu ilkbahar ekinoksunun başladığı noktadır.İlkbahar ve sonbahar ekinokslarında günler eşitlenir(12 saat gündüz, 12 saat gece). Bu nokta esas alındıktan sonra 360 Derece 12 eşit parçaya bölünerek burçlar kuşağı ortaya çıkartılır.\n" +
                "\nBatı Astrolojisi'nde burçlar\n" +
                "\nBatı astrolojisinin takımyıldızlarıyla bir alakası yoktur. Fakat, Hint Astrolojisi'nin vardır. Hint Astrolojisi takımyıldızlarını esas alır. Lakin Karakter Analizi yapılırken görülen tutarsızlık nedeniyle Batı'da(Hristiyan dünyasında) bu astroloji kabul görmemiştir. Hint astrolojisiyle Batı Astrolojisi arasında yaklaşık 23,5 derecelik bir kayma vardır. Mesela 31 Mart'ta doğan birisinin Güneşi (kişinin burcu olarak bildiği şey aslında Güneş burcudur) yaklaşık 10 derece Koç burcunda çıkarken, Hint astrolojisinde bu yaklaşık 23,5 derece geri kaydırıldığında Koç burcu olan kişi Balık burcu olmuş olur ki, bu Batı astrologları tarafından tutarlı görülmemiştir. Esasında Batı(Hristiyan) Astrolojisi temelini Arap Astrolojisi’nden alır. Göksel konumun matematiğini ilk geliştirenler Müslüman Araplar olmuştur. Trigonometri batı dünyasına Arap alimlerinden geçmiştir. Günümüzde kullanılan Uzay matematiğinin en önemli temel taşları Müslüman alimler tarafından keşfedilmiş, daha sonra bu bilgileri Hristiyanlar alıp geliştirmişlerdir." +
                "\nKehanet sanatı ve astroloji\n" +
                "\nGünümüzde astrologlar, Güneş'in, Ay'ın ve gezegenlerin insanın yaşamı üzerinde etkileri olduğunu ve buradan hareketle bir kişinin geleceğinin kestirilebileceğini öne sürerler.Bazı dergi ve gazetelerde, aynı burçta doğan herkes için ortak kehanetlerde bulunan yıldız falları yayımlanır. Babilliler İÖ 6.yüzyılda gezegenlerin gökyüzündeki hareketini gösteren haritalar yaptılar. Böylece Güneş ve Ay tutulmasının ne zaman olacağını önceden kestirebiliyorlardı. Astroloji Babil'den Eski Yunan'a, oradan da Mısır'a ve Hindistan'a geçti. Daha sonra bütün Asya ve Avrupa'ya yayıldı. İS 1066'da gökyüzünde parlak bir kuyrukluyıldız görünmüş ve bu alışılmadık olay insanları çok korkutmuştu.Bunu yorumlayan astrologlar yakın gelecekte bir kralın öleceğini ve çok önemli olayların yaşanacağını söylediler. Gerçekten de birkaç ay sonra, Hastings Savaşı'nda İngiltere Kralı Harold öldürülünce pek çok kişi bu kehanetin doğru olduğuna inandı. Oysa bugün Halley olarak adlandırılan bu kuyrukluyıldızın her 76 yılda bir Dünya çevresindeki yörüngesinden geçtiğini biliyoruz. Halley, her 75-76 yılda bir dünyaya yaklaşıyor ve çıplak gözle izlenebilir hale geliyor. Fakat, bu anlamlı rastlantıya Carl Gustav Jung 'Senkronizasyon Teorisi'ne göre 'anlamlı rastlantılar' adını vermektedir.\n" +
                "\nOsmanlı Dönemi'nde astroloji\n" +
                "\nOsmanlı dönemi klasik eserlerinden 1427'de yazılmış Murad-name, 51 maddede dönemin kültürel ve sosyal yapısını aktarırken astrolojiye ayrı bir madde ayrılmıştır. Maddede müneccim olmanın niteliklerinden, takvim hesaplamaya, yıldız ve gezegenlerin adlarına ve niteliklerine kadar genel olarak astroloji anlatılmaktadır. Müneccimbaşılık kurumuna erken Osmanlı döneminde rastlanmazken Fatih ve II.Bayezid bu dönemi açan kişiler olarak anılabilir. 17.asrın ikinci yarısından sonra hekimbaşılık kurumuna bağlanır. Saraydaki nüfuzları, Evliya Çelebi'nin IV. Murad devrindeki bir geçit töreninde müneccimbaşının Anadolu ve Rumeli kazaskerleriyle yan yana gitmesiyle örneklendirilebilir.\n" +
                "\nAstrolojinin tüketici davranışları üzerindeki etkileri\n" +
                "\nHer ne kadar astrolojinin somut olarak bilim olduğu bilim dünyası tarafından kabul edilmemiş olsa da bazı burçların belli başlı satın alma alışkanlıklarına sahip oldukları gözlemlenmektedir fakat bu alışkanlıkların belirginliği Placebo düzeyindedir ve hiçbir Rastgele Placebo Kontrollü Çalışma Astroloji'nin Placebo'dan öteye geçtiğini tespit edememiştir(Bazı çalışmalar aksini gösterse bile bunların ciddi ölçüde taraflı olduğu tespit edilmiştir.) Ayrıca bir burca ait olmanın kişide yarattığı psikolojik etkiyi(Placebo veya Nocebo şeklinde) kullanarak çeşitli pazarlama faaliyetleri yürütülmektedir.";
        }
    }
}
